name = "fairground"
chainid = "vega-fairground-202305051805"
testnet = true

[[nodes]]
name = "n00"
status = "unknown"
grpc = "api.n00.testnet.vega.rocks:3007"
rest = "https://api.n00.testnet.vega.rocks"
graphql = "https://api.n00.testnet.vega.rocks/graphql"

[[nodes]]
name = "n06"
status = "unknown"
grpc = "api.n06.testnet.vega.rocks:3007"
rest = "https://api.n06.testnet.vega.rocks"
graphql = "https://api.n06.testnet.vega.rocks/graphql"

[[nodes]]
name = "n07"
status = "unknown"
grpc = "api.n07.testnet.vega.rocks:3007"
rest = "https://api.n07.testnet.vega.rocks"
graphql = "https://api.n07.testnet.vega.rocks/graphql"

[[nodes]]
name = "n08"
status = "unknown"
grpc = "api.n08.testnet.vega.rocks:3007"
rest = "https://api.n08.testnet.vega.rocks"
graphql = "https://api.n08.testnet.vega.rocks/graphql"
