name = "mainnet"
chainid = "vega-mainnet-0011"
testnet = false

[[nodes]]
name = "Commodum"
status = "unknown"
grpc = "tls://vega-mainnet-data-grpc.commodum.io:443"
rest = "https://vega-mainnet-data.commodum.io"
graphql = "https://vega-mainnet-data.commodum.io/graphql"

[[nodes]]
name = "Nodes Guru"
status = "unknown"
grpc = "vega-data.nodes.guru:3007"
rest = "https://vega-data.nodes.guru:3008"
graphql = "https://vega-data.nodes.guru:3008/graphql"

[[nodes]]
name = "BHarvest"
status = "unknown"
grpc = "vega-data.bharvest.io:3007"
rest = "https://vega-data.bharvest.io"
graphql = "https://vega-data.bharvest.io/graphql"

[[nodes]]
name = "Path Rock Network"
status = "unknown"
grpc = "datanode.vega.pathrocknetwork.org:3007"
rest = "https://datanode.vega.pathrocknetwork.org"
graphql = "https://datanode.vega.pathrocknetwork.org/graphql"

[[nodes]]
name = "Aurora Edge"
status = "unknown"
grpc = "tls://vega-grpc.aurora-edge.com:443"
rest = "https://vega.aurora-edge.com"
graphql = "https://vega.aurora-edge.com/graphql"

[[nodes]]
name = "Darling"
status = "unknown"
grpc = "darling.network:3007"
rest = "https://darling.network"
graphql = "https://darling.network/graphql"

[[nodes]]
name = "Velvet P2P"
status = "unknown"
grpc = "tls://grpc.velvet.tm.p2p.org:443"
rest = "https://rest.velvet.tm.p2p.org"
grpahql = "https://gql.velvet.tm.p2p.org/graphql"

[[nodes]]
name = "Lovali"
status = "unknown"
grpc = "vega-grpc.mainnet.lovali.xyz:3007"
rest = "https://vega-rest.mainnet.lovali.xyz"
graphql = "https://vega-query.mainnet.lovali.xyz/graphql"

[[nodes]]
name = "AnyValid"
status = "unknown"
grpc = "vega-mainnet.anyvalid.com:3007"
rest = "https://vega-mainnet.anyvalid.com"
graphql = "https://vega-mainnet.anyvalid.com/graphql"

[[nodes]]
name = "Staking Cabin"
status = "unknown"
grpc = "vega.mainnet.stakingcabin.com:3007"
rest = "https://vega.mainnet.stakingcabin.com:3008"
graphql = "https://vega.mainnet.stakingcabin.com:3008/query"

