name = "Matts Test 1 Oracle"
url ="https://google.com"
description_md = """
# Markdown describing the oracle provider

Some markdown describing the oracle provider.

Twitter: @FacesPics2
"""
isTestNetworkOnly = true # optional flag to indicate if market should or should not be used by applications connected to mainnet

[oracle]
id = "a252d1f65201b4af162192e663b50e917328f816868f08bb9a00649571709db4"
public_key = "70d14a321e02e71992fd115563df765000ccc4775cbe71a0e2f9ff5a3b9dc680"
status =  "GOOD"
status_reason = ""
first_verified = 2022-01-01T00:00:00Z
last_verified = 2022-12-31T00:00:00Z

[[proofs]]
type = "twitter"
format = "URL"
url = "https://twitter.com/vegaprotocol/status/956833487230730241"
available = true

[[proofs]]
type = "web"
format = "URL"
url = "https://acme.io/proof.txt"
available = true

[[proofs]]
type = "github"
format = "URL"
url = "https://github.com/mattrussell36/somerepo"
available = true

[[proofs]]
type = "key"
format = "signed_message"
pubkey = "70d14a321e02e71992fd115563df765000ccc4775cbe71a0e2f9ff5a3b9dc680"
message = "1tW+4ogc7OKDGNZQdOdE98vZvIwzh/di5iW8vzKD7fezr4LQ87Wh/AA0zeRa1G9YHyYaW2CZ9VHC6KsS2Bi9Aw="
available = true