name = "Uniswap price sources"
url ="https://github.com/jeremyletang/uniswap_price_source"
description_markdown = """
# Uniswap price source

A smart contract providing prices from uniswap v3 pools
"""

[oracle]
source_chain = "Ethereum"
source_chain_id = "1"
type = "eth_address"
eth_address= "0xBEDBC6302eAFFd4032Dd1DF94e326F7ecb9Ff4f9"
status = "GOOD"
status_reason = ""
first_verified = 2023-05-22T00:00:00Z
last_verified = 2023-05-22T00:00:00Z

[[proofs]]
type = "web"
format = "url"
url = "https://etherscan.io/address/0xbedbc6302eaffd4032dd1df94e326f7ecb9ff4f9#code"
available = true
