name = "Test oracle"
url ="https://zombo.com"
description_markdown = """
Some markdown describing the oracle provider.

Twitter: @FacesPics2
"""

[oracle]
type = "eth_address"
eth_address= "0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BD"
status = "GOOD"
status_reason = ""
first_verified = 2023-02-28T00:00:00Z
last_verified = 2023-02-28T00:00:00Z