name = "Test oracle"
url ="https://zombo.com"
description_markdown = """
Some markdown describing the oracle provider.

Twitter: @FacesPics2
"""

[oracle]
type = "eth_address"
eth_address= "0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC"
status = "GOOD"
status_reason = ""
first_verified = 2023-02-28T00:00:00Z
last_verified = 2023-02-28T00:00:00Z

[[proofs]]
type = "eth_address"
format = "signed_message"
eth_address = "0x949AF81E51D57831AE52591d17fBcdd1014a5f52"
message = "SOMEHEX"
available = true