name = "Another oracle"
url ="https://zombo.com"
description_markdown = """
Some markdown describing the oracle provider.

Twitter: @FacesPics2
"""

[oracle]
type = "public_key"
public_key = "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f"
status = "GOOD"
status_reason = ""
first_verified = 2022-01-01T00:00:00Z
last_verified = 2022-12-31T00:00:00Z

[[proofs]]
type = "twitter"
format = "url"
url = "https://twitter.com/vegaprotocol/status/956833487230730241"
available = true

[[proofs]]
type = "web"
format = "url"
url = "https://acme.io/proof.txt"
available = true

[[proofs]]
type = "github"
format = "url"
url = "https://github.com"
available = true

[[proofs]]
type = "public_key"
format = "signed_message"
public_key = "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f"
message = "SOMEHEX"
available = true

[[proofs]]
type = "eth_address"
format = "signed_message"
eth_address = "0x949AF81E51D57831AE52591d17fBcdd1014a5f52"
message = "SOMEHEX"
available = true