name: Process oracle providers

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  process_oracles_providers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.VEGA_CI_BOT_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Use Node.js 16
        id: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - name: Install root dependencies
        run: yarn install
      - name: Process oracle providers
        run: npm run generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: process oracle providers"
          commit_options: "--no-verify --signoff"
          skip_fetch: true
          skip_checkout: true
