---


name: "Quality checks"

"on":
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  spellcheck:
    name: "Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3.5.3

      - name: "Run PySpelling"
        uses: rojopolis/spellcheck-github-actions@0.33.1
        with:
          task_name: Markdown

  markdownlint:
    name: "Markdownlint"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3.5.3

      - name: "Run Markdownlint"
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .github/workflows/config/markdownlint.json
          ignore_path: .github/workflows/config/markdownlintignore
